# Configuration for PR Agent
# All configuration options: https://github.com/qodo-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml

[config]
model = "gemini/gemini-2.5-pro-preview-03-25"
max_model_tokens = 1048576

enable_auto_approval=true
auto_approve_for_low_review_effort=1
auto_approve_for_no_suggestions=true

fallback_models = [
    "gemini/gemini-2.5-flash-preview-04-17",
    "gemini/gemini-2.0-flash",
]

[pr_reviewer] # /review #
model = "gemini/gemini-2.5-pro-preview-03-25"
extra_instructions = """
(1) Don't suggest to add try-except block
(2) Answer in german
"""

[pr_description] # /describe #
model = "gemini/gemini-2.5-flash-preview-04-17"
generate_ai_title=true
extra_instructions = ""

[pr_code_suggestions] # /improve #
model = "gemini/gemini-2.5-pro-preview-03-25"
extra_instructions = """
(1) Don't suggest to add try-except block
"""

