name: PR Agent
on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: PR Agent
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GOOGLE_AI_STUDIO__GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          #OPENAI_API_KEY
          GOOGLE_AI_STUDIO__GEMINI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          CONFIG__MODEL: "gemini/gemini-2.0-flash"
          github_action_config.auto_review: "false"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "false"
