name: PR Agent
on:
  pull_request:
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: PR Agent
    steps:
      - name: PR Agent action step
        id: pragent
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI.KEY: ${{ secrets.GEMINI_API_KEY }}
          OPENAI.API_BASE: "https://generativelanguage.googleapis.com/v1beta/openai/"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG.MODEL: "gemini-2.0-flash"
          CONFIG.CUSTOM_MODEL_MAX_TOKENS: 1048576
          github_action_config.auto_review: "false"
          github_action_config.auto_describe: "false"
          github_action_config.auto_improve: "false"
